# Generated by Django 3.2.15 on 2022-10-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('project_owner', 'project_owner'), ('admin', 'admin'), ('manager', 'manager'), ('reviewer', 'reviewer'), ('implementer', 'implementer'), ('coordinator', 'coordinator')], default='project_owner', max_length=25),
        ),
    ]
