# Generated by Django 4.1.2 on 2022-10-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('Manager', 'Manager'), ('Reviewer', 'Reviewer'), ('Implementer', 'Implementer'), ('Coordinator', 'Coordinator')], default='user', max_length=25),
        ),
    ]
