# Generated by Django 3.2.15 on 2022-10-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectowner',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='projectowner',
            name='location',
        ),
    ]
