# Generated by Django 3.2.15 on 2022-10-30 13:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_auto_20221030_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_description', models.TextField(max_length=255)),
                ('url', models.TextField(max_length=255)),
                ('title', models.TextField()),
                ('technologies_to_used', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('project_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.projectowner')),
            ],
        ),
    ]
