# Generated by Django 3.2.15 on 2022-10-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=100)),
                ('proj_desc', models.TextField()),
                ('proj_file', models.ImageField(upload_to='projects/')),
                ('proj_url', models.URLField()),
                ('proj_date', models.DateTimeField(auto_now_add=True)),
                ('proj_type', models.CharField(max_length=100)),
                ('proj_comments', models.TextField(blank=True, null=True)),
                ('proj_status', models.CharField(max_length=100)),
            ],
        ),
    ]
